apiVersion: v1
kind: Secret
metadata:
  name: {{ include "activepieces.fullname" . }}-secrets
  labels:
    {{- include "activepieces.labels" . | nindent 4 }}
type: Opaque
data:
  encryption-key: {{ .Values.activepieces.encryptionKey | default (randAlphaNum 32 | b64enc) | b64enc | quote }}
  jwt-secret: {{ .Values.activepieces.jwtSecret | default (randAlphaNum 64 | b64enc) | b64enc | quote }} 