name: CI
on:
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-extra-large-js" --agents

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      - name: List all nx targets
        run: npx nx show projects --all
      
      - name: Get changed files
        id: changed-files
        run: echo "files=$(git diff --name-only HEAD origin/main | tr '\n' ' ')" >> $GITHUB_OUTPUT
      
      - name: Extract pieces projects from changed files
        id: extract-pieces
        run: |
          PIECES=$(echo "${{ steps.changed-files.outputs.files }}" | grep -o "pieces-[^ /]*" | sort -u | tr '\n' ',' | sed 's/,$//')
          echo "pieces_projects=$PIECES" >> $GITHUB_OUTPUT

      - run: npx nx affected --target=lint --exclude="pieces-*" --agents --parallel
      
      - name: Lint changed pieces projects
        if: steps.extract-pieces.outputs.pieces_projects != ''
        run: npx nx run-many --target=lint --projects="${{ steps.extract-pieces.outputs.pieces_projects }}" --agents --parallel
        
      - run: npx nx affected --target=build -c production --agents --parallel
      
      - name: Build changed pieces projects
        if: steps.extract-pieces.outputs.pieces_projects != ''
        run: npx nx run-many --target=build -c production --projects="${{ steps.extract-pieces.outputs.pieces_projects }}" --agents --parallel
        
      - run: npx nx run-many --target=test --projects=engine,shared,server-api --agents --parallel