name: Auto Merge Crowdin PRs Action

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  auto-merge-bot-pr:
    runs-on: ubuntu-latest
    
    if: |
      github.event.pull_request.user.login == 'AbdulTheActivePiecer' &&
      github.event.pull_request.head.ref == 'l10n_main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Add label to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['auto-merge', 'translations','skip-changelog']
            })
      
      - name: Fetch main branch
        run: git fetch origin main:main
      
      - name: Run Node.js script
        run: |
          echo "Running Node.js script..."
          npm run bump-translated-pieces
      
      - name: Check for changes and commit
        run: |
          # Check if there are any changes
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "Changes detected, committing..."
            
            # Configure git
            git config --local user.email "abdulyki@activepieces.com"
            git config --local user.name "AbdulTheActivePiecer"
            
            # Add all changes
            git add .
            
            # Commit with a descriptive message
            git commit -m "chore: auto bump translated pieces"
            
            # Push changes back to the PR branch
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
            
            echo "Changes committed and pushed to PR branch"
          else
            echo "No changes detected, skipping commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update PR branch with latest main
        uses: actions/github-script@v7
        with:
          script: |
            // Fetch the latest ref to ensure we have the current HEAD
            await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${context.payload.pull_request.head.ref}`
            });
            
            await github.rest.pulls.updateBranch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
        env:
          GITHUB_TOKEN: ${{ secrets.CROWDIN_PRS }}

      - name: Auto merge PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'merge'
            })
        env:
          GITHUB_TOKEN: ${{ secrets.CROWDIN_PRS }}
