name: Auto Merge Bot PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  auto-merge-bot-pr:
    runs-on: ubuntu-latest
    
    if: |
      github.event.pull_request.user.login == 'AbdulTheActivePiecer' &&
      github.event.pull_request.head.ref == 'l10n_main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Add label to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['auto-merge', 'translations','skip-changelog']
            })
      
      - name: Fetch main branch
        run: git fetch origin main:main
      
      - name: Run Node.js script
        run: |
          echo "Running Node.js script..."
          npm run bump-translated-pieces
      
      - name: Auto merge PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'
            })
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
