name: E2E Tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Run Checkly tests
        id: checkly-tests
        run: npx checkly test --config=packages/tests-e2e/checkly.config.ts --reporter=github --record
        env:
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
          CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}
          E2E_EMAIL: ${{ secrets.E2E_EMAIL }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD }}
          E2E_INSTANCE_URL: ${{ secrets.E2E_INSTANCE_URL }}

      - name: Deploy Checkly config
        if: steps.checkly-tests.outcome == 'success'
        run: npx checkly deploy --config=packages/tests-e2e/checkly.config.ts
        env:
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
          CHECKLY_ACCOUNT_ID: ${{ secrets.CHECKLY_ACCOUNT_ID }}

      - name: Create summary
        run: cat checkly-github-report.md > $GITHUB_STEP_SUMMARY
        if: always()

      - name: Notify Discord on failure
        if: failure()
        run: |
          SUMMARY=""
          if [ -f checkly-github-report.md ]; then
            SUMMARY=$(node tools/scripts/format-checkly-report.js checkly-github-report.md)
          else
            SUMMARY=$(node -e "console.log(JSON.stringify('❌ **Checkly E2E tests are failing in the workflow!**'))")
          fi
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": $SUMMARY}" \
            https://discord.com/api/webhooks/1346795060116586567/e-1-MwQEykv6fYGC28mqqVU-2VzFif9NgGFtuNmCW7IL_MUTgBwXJY-4YYkZo8BEv00m