name: Generate Translation Files for Community Pieces and UI

on:
  schedule:
    - cron: '5 15 * * *'
  workflow_dispatch:

jobs:
  shard-0:
    uses: ./.github/workflows/reusable-generate-translations-shard.yml
    with:
      shard_index: 0
      shard_total: 6
      branch_name: auto/translation-files-${{ github.run_id }}
    secrets: inherit

  shard-1:
    needs: shard-0
    uses: ./.github/workflows/reusable-generate-translations-shard.yml
    with:
      shard_index: 1
      shard_total: 6
      branch_name: auto/translation-files-${{ github.run_id }}
    secrets: inherit

  shard-2:
    needs: shard-1
    uses: ./.github/workflows/reusable-generate-translations-shard.yml
    with:
      shard_index: 2
      shard_total: 6
      branch_name: auto/translation-files-${{ github.run_id }}
    secrets: inherit

  shard-3:
    needs: shard-2
    uses: ./.github/workflows/reusable-generate-translations-shard.yml
    with:
      shard_index: 3
      shard_total: 6
      branch_name: auto/translation-files-${{ github.run_id }}
    secrets: inherit

  shard-4:
    needs: shard-3
    uses: ./.github/workflows/reusable-generate-translations-shard.yml
    with:
      shard_index: 4
      shard_total: 6
      branch_name: auto/translation-files-${{ github.run_id }}
    secrets: inherit

  shard-5:
    needs: shard-4
    uses: ./.github/workflows/reusable-generate-translations-shard.yml
    with:
      shard_index: 5
      shard_total: 6
      branch_name: auto/translation-files-${{ github.run_id }}
    secrets: inherit

  finalize:
    needs: shard-5
    uses: ./.github/workflows/reusable-finalize-translations-pr.yml
    with:
      branch_name: auto/translation-files-${{ github.run_id }}
    secrets: inherit
