name: PR E2E Tests

on:
  pull_request:
    branches:
      - gh-actions-test-branch
    types: [opened, synchronize, reopened]

permissions:
  actions: write
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  trigger-e2e:
    name: Trigger E2E Tests
    uses: ./.github/workflows/e2e.yml